import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { Suisse } from "../fonts";
import Navbar from "@/components/Layout/Navbar/Navbar";
import { GlobalContextProvider } from "@/context/GlobalContext/GlobalContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Agrify Carbon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GlobalContextProvider>
      <html lang="en">
        <head>
          <link
            rel="icon"
            href="../assets/agrify_icon.svg"
            type="image/svg+xml"
          />
        </head>
        <body className={`${Suisse.className} ${inter.className}`}>
          <Navbar />
          <Providers>{children}</Providers>
        </body>
      </html>
    </GlobalContextProvider>
  );
}
